name: Node.js CI - with cache and shared action

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Build Node
        uses: MGGTestingGitOrganization/GHA.workflows/.github/actions/build-node@main
