name: Custom token
on:
  workflow_dispatch:
    inputs:
      audience:
        type: string
        required: true
        default: GabyCustomAudience test
jobs:
  get-token:
    name: token
    uses: MGGTestingGitOrganization/GHA.Private.Templates/.github/workflows/gha.workflows.manual-test-reusable-oidc-token.yml@main
    permissions:
      id-token: write
    with:
      audience: ${{ inputs.audience}}
  